### ISSUE TITLE
Not working with Grails 3.3.3.

### ISSUE THREAD

**Issue by pjdvmalan** [opengreenfield/greenfield#2]

**Comment by andrelbuzzo** [comment]
It isn't working because Shiro hasn't been upgraded to Grails latest version (or any 3.3.x).
I haven't found any solution until now, you can check [Spring Shiro's repo](https://www.github.com/grails-plugins/grails-spring-security-shiro/issues), there's a ticket opened on 14 Nov 2017 by githubLixiaoyu, and there's no solution so far.
I think Grails community is starting to die.

**Comment by pjdvmalan** [comment]
For Grails to stay a viable framework, backwards incompatible changes are unfortunately required.

One can expect that it will take a bit of time for all the major plugins to be upgraded. It's also up to the community to help with the upgrade - but it does take time & commitment, especially with the more complicated plugins like this one. 

I see that @sdelamo has been assigned to the ticket, so hopefully there will be some movement on this.

**Comment by mcroteau** [comment]
Current version Grails 3.3.4
